### ISSUE TITLE
psycopg2.errors.UndefinedColumn: column

### ISSUE THREAD

**Issue by janbesler** [FlorianK13/python-mastrsql#1]
psycopg2.errors.UndefinedColumn: column "Kraftwerksnummer" of relation "einheitensolar" does not exist
LINE 1: ...eltigeStilllegung", "DatumWiederaufnahmeBetrieb", "Kraftwerk...
.
.
.
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/miniconda3/lib/python3.9/site-packages/mastrsql-0.0.post1.dev18+g6142ac5-py3.9.egg/mastrsql/mastr.py", line 192, in to_sql
    missing_column = str(err).split("«")[0].split("»")[1]
IndexError: list index out of range

While parsing the first file from einheitensolar the error above occurred. Is this problem upstream or do you have an idea how to handle it?

**Comment by FlorianK13** [comment]
I'll have a look at it within the next days. In the meantime, you can set the parameter exclude_tables=["einheitensolar"] in the to_sql function, so that the computer can read the other data into your database.

**Comment by janbesler** [comment]
Thank you!
I tried your suggestion, also with include_tables=["einheitenwind"] in the mastr.py file, but it did not help. I ran in the same error again at the same position.

**Comment by FlorianK13** [comment]
I'm currently merging the code into [open_Mastr feature 202](https://github.com/OpenEnergyPlatform/open-MaStR/tree/feature-%23202-xmlparser). There I cannot reproduce the error. 
Can you clone the open_Mastr feature 202 branch and [pip install it locally](https://stackoverflow.com/questions/41535915/python-pip-install-from-local-dir/41537134)?
Then, the following code should create an sqlite database of the mastr locally in ~/.open-MaStR/data/sqlite

from open_mastr.mastr import Mastr
db = Mastr()
db.download(method="bulk")

If you only want a specific table, you can once again set the parameter include_tables = ["tablename"] in the download() function. We're currently working on a stable open_mastr package that we also want to publish on pypi, so also consider using that one as soon as it is out.
